on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  changed-paths:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.changed-paths.outputs.all_changed_files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: changed directories
        uses: tj-actions/changed-files@v44
        with:
          path: './charts'
          dir_names: true

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-paths.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done

#      - name: changed paths
#        uses: dorny/paths-filter@v3
#        id: changed
#        with:
#          filters: |
#            changed:
#              - 'charts/**'

  linting:
    needs: changed-paths
    strategy:
      matrix:
        package: ${{ fromJson(needs.changed-paths.outputs.changed) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint
        run: |
          helm lint ./charts/${{ matrix.package }}