on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  changed-paths:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.changed.outputs.changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: changed paths
        uses: dorny/paths-filter@v3
        id: changed
        with:
          filters: |
            changed:
              - 'charts/**'

    linting:
      needs: changed-paths
      strategy:
        matrix:
          package: ${{ fromJson(needs.changed-paths.outputs.changed) }}
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Lint
          run: |
            helm lint ./charts/${{ matrix.package }}