on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  changed-paths:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.changed-path.outputs.all_changed_files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: changed directories
        id: changed-path
        uses: tj-actions/changed-files@v44
        with:
          path: './charts'
          dir_names: true
          dir_names_max_depth: '1'

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-path.outputs.all_changed_files }}
        run: |
          echo "Hello World"
          echo "$ALL_CHANGED_FILES"
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done

  linting:
    needs: changed-paths
    strategy:
      matrix:
        package: ${{ fromJson(needs.changed-paths.outputs.changed) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint
        run: |
          echo "Linting ${{ matrix.package }}"
          helm lint ./charts/${{ matrix.package }}